# Generated by Django 3.0.6 on 2020-05-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20200530_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
