# Generated by Django 3.0.6 on 2020-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Examiner'), (2, 'Student')]),
        ),
    ]
